# Key 是QQ号/QQ群号，Value是规则名
pool: 
  389617786: NORMAL
  597550140: NORMAL
# Key 规则名，Value是卡池规则
rules: 
  限时寻访深悼: '浊心斯卡蒂|凯尔希:0.014;赤冬:0.04;******:0.006;*****:0.04;****:0.48;other:0.42'
  NORMAL: '#NORMAL;******:0.02;*****:0.08;****:0.48;***:0.42'